/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_cracker_free: (a: number, b: number) => void;
export const __wbg_enchantmenttableinfo_free: (a: number, b: number) => void;
export const __wbg_manipulator_free: (a: number, b: number) => void;
export const __wbg_utilities_free: (a: number, b: number) => void;
export const cracker_addInput: (a: number, b: number) => void;
export const cracker_contains: (a: number, b: number) => number;
export const cracker_firstInput: (a: number, b: number, c: number) => void;
export const cracker_new: (a: number, b: number) => number;
export const cracker_possible_seeds: (a: number) => number;
export const cracker_reset: (a: number) => void;
export const cracker_seed: (a: number) => number;
export const enchantmenttableinfo_new: (a: number, b: number, c: number, d: number) => number;
export const manipulator_changeSeed: (a: number, b: number, c: number) => number;
export const manipulator_new: (a: number, b: number) => number;
export const manipulator_player_seed: (a: number) => any;
export const manipulator_reset: (a: number, b: number) => void;
export const manipulator_simulate: (a: number, b: number, c: number, d: number, e: number) => any;
export const manipulator_updateItem: (a: number, b: number, c: number) => void;
export const manipulator_updateSeed: (a: number, b: number, c: number, d: number) => number;
export const utilities_areEnchantmentsCompatible: (a: number, b: number, c: number) => number;
export const utilities_enchantmentIntroducedVersion: (a: number) => number;
export const utilities_getEnchantments: (a: number) => any;
export const utilities_getItems: (a: number) => any;
export const utilities_getMaxLevelInTable: (a: number, b: number) => number;
export const utilities_isTreasure: (a: number) => number;
export const utilities_itemIntroducedVersion: (a: number) => number;
export const utilities_materialIntroducedVersion: (a: number) => number;
export const __wbg_enchantmentinstance_free: (a: number, b: number) => void;
export const __wbg_get_enchantmentinstance_enchantment: (a: number) => number;
export const __wbg_get_enchantmentinstance_level: (a: number) => number;
export const __wbg_set_enchantmentinstance_enchantment: (a: number, b: number) => void;
export const __wbg_set_enchantmentinstance_level: (a: number, b: number) => void;
export const enchantmentinstance_new: (a: number, b: number) => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_start: () => void;
