# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.3
        with:
          path: ./scripts/temp
          key: ${{ runner.os }}-script-temp
      - name: rust-toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      - run: sudo apt-get install binaryen jq
      - name: compile wasm
        run: |
          chmod +x ./scripts/deploy.sh
          ./scripts/deploy.sh
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.2.0
        with:
          target_branch: page
          build_dir: ./www/
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      
